//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalAutomation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADLISAGLIKKURULUYOL
    {
        public ADLISAGLIKKURULUYOL()
        {
            this.ADLISAGLIKKURULURESIMLER = new HashSet<ADLISAGLIKKURULURESIMLER>();
            this.DOSYALAR = new HashSet<DOSYALAR>();
        }
    
        public int AdliSaglikKuruluYolID { get; set; }
        public string AdliSaglikKuruluYolKayit { get; set; }
    
        public virtual ICollection<ADLISAGLIKKURULURESIMLER> ADLISAGLIKKURULURESIMLER { get; set; }
        public virtual ICollection<DOSYALAR> DOSYALAR { get; set; }
    }
}
