//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalAutomation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADLISAGLIKKURULURESIMLER
    {
        public int AdliSaglikKuruluResimID { get; set; }
        public int AdliSaglikKuruluYolID { get; set; }
        public string AdliSaglikKuruluResim { get; set; }
    
        public virtual ADLISAGLIKKURULUYOL ADLISAGLIKKURULUYOL { get; set; }
    }
}
