//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLUMLER
    {
        public BOLUMLER()
        {
            this.DOSYALARs = new HashSet<DOSYALAR>();
        }
    
        public int Bolumid { get; set; }
        public string BolumAdı { get; set; }
    
        public virtual ICollection<DOSYALAR> DOSYALARs { get; set; }
    }
}
