//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalAutomation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUAYENEEPIKRIZYOL
    {
        public MUAYENEEPIKRIZYOL()
        {
            this.MUAYENEEPIKRIZRESIMLERs = new HashSet<MUAYENEEPIKRIZRESIMLER>();
            this.DOSYALAR = new HashSet<DOSYALAR>();
        }
    
        public int MuayeneEpikrizYolID { get; set; }
        public string MuayeneEpikrizYolKayit { get; set; }
    
        public virtual ICollection<MUAYENEEPIKRIZRESIMLER> MUAYENEEPIKRIZRESIMLERs { get; set; }
        public virtual ICollection<DOSYALAR> DOSYALAR { get; set; }
    }
}
