//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUAYENEEPIKRIZRESIMLER
    {
        public int MuayeneEpikrizResimID { get; set; }
        public int MuayeneEpikrizYolID { get; set; }
        public string MuayeneRaporResimAd { get; set; }
    
        public virtual MUAYENEEPIKRIZYOL MUAYENEEPIKRIZYOL { get; set; }
    }
}
