//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalAutomation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TANILAR
    {
        public TANILAR()
        {
            this.DOSYALAR = new HashSet<DOSYALAR>();
        }
    
        public int Taniid { get; set; }
        public string TaniAdi { get; set; }
        public string ICD10Kodu { get; set; }
    
        public virtual ICollection<DOSYALAR> DOSYALAR { get; set; }
    }
}
