//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalAutomation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TETKIKRAPORRESIMLER
    {
        public int TetkikRaporResimID { get; set; }
        public int TetkikRaporYolID { get; set; }
        public string TetkikRaporResimAd { get; set; }
    
        public virtual TETKIKRAPORYOL TETKIKRAPORYOL { get; set; }
    }
}
